### ISSUE TITLE
No Tag Audio Files

### ISSUE THREAD

**Issue by PiSaucer** [Offroaders123/Art-Gen#1]
I tried to upload a `.wav` file to [offroaders123.github.io/Art-Gen/](https://offroaders123.github.io/Art-Gen/) and does nothing. After inspect, I get:

```
Uncaught (in promise) > Object
info:  "No suitable tag reader found"
type: "tagFormat"
```

I only assume the issue happens since `.wav` files are unable to have any metatag data. 

Can there be a mode to manually type out the metadata and upload an album cover?

**Comment by Offroaders123** [comment]
> I only assume the issue happens since `.wav` files are unable to have any metatag data.

Yes, you're right there. The current code only handles files that have embedded music metadata.

> Can there be a mode to manually type out the metadata and upload an album cover?

That's a great idea! I guess I only pictured doing it for direct song files themselves. But, being able to use the same workflow for just the metadata itself is also a super useful thing to have.

**Comment by Offroaders123** [comment]
I'm starting to export my own songs as lossless `.wav` files now, so I'm about to begin running into this issue myself soon, too.

So, I will look into getting this working in the next week possibly.

**Comment by Offroaders123** [comment]
Started adding a few options today in the app to provide your own song names to generate thumbnails for a given artwork image.

It's not fully implemented yet, so the new form controls won't do anything additional, quite yet.

**Comment by Offroaders123** [comment]
Alright, this has been added now! The user interface for the app is still not the best it can be, so I want to work on that as some of the next updates. All of the functionality for providing your own custom metadata is now there, though!
